env:
  global:
    - NODE_ENV=test
    - API_SERCRET_KEY=secret
    - DATABASE_URL_TEST=postgres://postgres@localhost:5432/mentorspace_test
language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE mentorspace_test;' -U postgres
  - npm run createTables
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:CI
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage